feat: add sorting by fields to SCSI
linkedin/datahub-gma pull request #101
Opened 2021-06-09 14:45 UTC by kaliang1

This change adds sorting by fields to SCSI. A new parameter called IndexSortCriterion was added to the filter method, which specifies the aspect, path, value column, and sorting order.

In BaseLocalDAO, the signature of the abstract method `listUrns` was modified to include the sort criterion parameter.

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2021-06-10 20:35 UTC, jywadhwani requested changes

2021-06-10 20:58 UTC, kaliang1 commented on dao-api/src/main/pegasus/com/linkedin/metadata/query/IndexSortCriterion.pdl
> +  aspect: string
I think the `aspect` and `path` are needed to specify the field that the user wants to sort on. For example, if a user wanted to sort by the aspect AspectFoo and the path “/id” with the column stringval, then the query would be:

`SELECT DISTINCT(t0.urn), tsort.stringval FROM metadata_index t0 INNER JOIN metadata_index tsort ON t0.urn = tsort.urn WHERE tsort.aspect = “AspectFoo” and tsort.field = “/id” order by tsort.stringval ASC;`

2021-06-11 17:37 UTC, jywadhwani commented on dao-api/src/main/pegasus/com/linkedin/metadata/query/IndexSortCriterion.pdl
> +  aspect: string
Actually you could use the `IndexCriterion` itself to specify the filter and then sort by the column. The current limitation is that `IndexCriterion` requires you to specify a value along with path.

If I make that change, i.e. provide (aspect, path) in the `IndexCriterion` without providing the `value`, do you think we should be fine with just providing the sort column and sort order?

2021-06-11 17:53 UTC, jywadhwani requested changes

2021-06-11 17:53 UTC, jywadhwani commented on restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java
> +  @Finder(FINDER_FILTER)
Do you think we can mark this finder method as deprecated? `FINDER_FILTER_SORT` has sort params as optional so we can leverage that method directly.

2021-06-11 17:53 UTC, jywadhwani commented on restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java
>        @PagingContextParam @Nonnull PagingContext pagingContext) {
Since we are creating a new finder method, I will use this opportunity to remove `pagingContext` and replace it with `count` since we are using cursor based pagination here.

2021-06-11 18:05 UTC, kaliang1 commented on dao-api/src/main/pegasus/com/linkedin/metadata/query/IndexSortCriterion.pdl
> +  aspect: string
That should work!

2021-06-11 19:04 UTC, keremsahin1 commented on dao-api/src/main/pegasus/com/linkedin/metadata/query/IndexSortCriterion.pdl
> +  aspect: string
When you get multiple aspects, how does sorting work? Do you only sort AspectFoo in this case?

2021-06-11 19:10 UTC, kaliang1 commented on dao-api/src/main/pegasus/com/linkedin/metadata/query/IndexSortCriterion.pdl
> +  aspect: string
Yes, it only sorts by the aspect provided so it will only sort AspectFoo.

2021-06-14 22:54 UTC, jywadhwani requested changes

2021-06-14 22:54 UTC, jywadhwani commented on dao-api/src/main/pegasus/com/linkedin/metadata/query/IndexSortCriterion.pdl
> +  column: IndexColumn
This is a storage specific information i.e. how we store the values. I wouldn't assume the client should know this information - also this mapping of value type to column could change.
If you know the aspect and path spec, you should be able to get the value type? On the server side you can then map it to the relevant SQL column?

2021-06-14 23:03 UTC, jywadhwani commented on dao-api/src/main/pegasus/com/linkedin/metadata/query/IndexSortCriterion.pdl
> +  aspect: string
Sounds good.
I guess you missed a `WHERE` clause on `t0` in your above query. But I get what your requirement is.

2021-06-16 21:55 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    final EbeanMetadataIndex record = _server.find(EbeanMetadataIndex.class)
querying the DB to get the value type/column is not optimal approach, will slow down the read path. Ideally we should be able to obtain the value type given an aspect and path. Can we explore feasibility of that approach?

2021-06-17 17:22 UTC, jywadhwani requested changes
This looks good, thanks for the change.
Added some more comments.

2021-06-17 17:22 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    pathSpecAsString = leadingSpaceslashPattern.matcher(pathSpecAsString).replaceAll("");
again there seems to be repeated code here as well https://github.com/linkedin/datahub-gma/blob/master/dao-api/src/main/java/com/linkedin/metadata/dao/utils/RecordUtils.java#L409
Can we consolidate this logic in a util method that both can use? You could put this method in `RecordUtils` only.

2021-06-17 17:22 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +      throw new IllegalArgumentException("Invalid sort criterion " + indexSortCriterion);
Same here, let's add more details on why the criterion is invalid.

2021-06-17 20:11 UTC, jywadhwani requested changes

2021-06-17 20:11 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  private <ASPECT extends RecordTemplate> String getSortingColumn(@Nonnull IndexSortCriterion indexSortCriterion) {
Can we add some tests for this method? We should be able to test for different fields such as an array of primitives, array of records, enum, union, etc.

2021-06-17 20:11 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  private <ASPECT extends RecordTemplate> ASPECT getAspectFromString(@Nonnull String aspectClassString) {
possible to move this method as well in `RecordUtils`?

2021-06-17 20:47 UTC, keremsahin1 commented on dao-api/src/main/java/com/linkedin/metadata/dao/utils/RecordUtils.java
> +  public static String[] getPathSpecAsArray(@Nonnull String pathSpecAsString) {
Please make sure to add tests for any public util methods

2021-06-17 20:47 UTC, keremsahin1 commented on dao-api/src/main/java/com/linkedin/metadata/dao/utils/RecordUtils.java
> +    String[] pathSpecAsArray = getPathSpecAsArray(pathSpecAsString);
nit: final

2021-06-17 23:03 UTC, jywadhwani requested changes

2021-06-17 23:03 UTC, jywadhwani commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +    // 7. array corresponds to string column
So if this field is an array of N integers (say), what does sorting by ascending order of this array mean here?

2021-06-17 23:03 UTC, jywadhwani commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +    // 8. union corresponds to string column
Here `unionField` is a union of two record templates. What does `/unionField` path imply? which field do we wish to sort on?

2021-06-17 23:03 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    if (indexSortCriterion != null) {
`sortColumn` should also be a non-empty string here for this block to execute?

2021-06-17 23:03 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    if (indexSortCriterion != null) {
same here, `sortColumn` should be non-empty string here?

2021-06-17 23:58 UTC, kaliang1 commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +    // 7. array corresponds to string column
I think it would sort by the string literal of the array. It doesn't make too much sense to sort urns based on an aspect that is an array or union type so I will remove this case.

2021-06-18 20:15 UTC, jywadhwani commented on dao-api/src/main/java/com/linkedin/metadata/dao/utils/RecordUtils.java
> +  public static String[] getPathSpecAsArray(@Nonnull String pathSpecAsString) {
Looks like this has been added.

2021-06-18 20:17 UTC, jywadhwani commented on dao-api/src/test/java/com/linkedin/metadata/dao/utils/RecordUtilsTest.java
> +    String ps1 = "/test/path";
Let us also add a test for an array of records i.e. `/recordArray/*/<recordField>` ?

2021-06-18 22:26 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +      if (part.equals("*")) {
`*` would mean a path corresponding to an array. We shouldn't be supporting it right?

2021-06-18 22:26 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +      } else if (dataSchema.getDereferencedType() == DataSchema.Type.ARRAY) {
this is if the field is of type array? Are we allowing sort over an array of elements?

2021-06-18 22:26 UTC, jywadhwani commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +    // 10. array of records
this shouldn't be supported either IMO.

2021-06-18 22:26 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    if (indexSortCriterion != null && !sortColumn.isEmpty()) {
Better way is to only take `IndexSortCriterion` as input in function `constructSQLQuery` and compute sort column within this method.
Then you can only check if sort column is non empty in this condition.

2021-06-18 22:27 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    if (indexSortCriterion != null && !sortColumn.isEmpty()) {
Or you could check if `indexSortCriterion != null` - that should work too. I suggested having both conditions in my previous review, but it looks like `indexSortCriterion != null` implies `!sortColumn.isEmpty()`.

2021-06-18 22:33 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    if (indexSortCriterion != null) {
Sorry for the confusion here. Didn't realize `indexSortCriterion != null` implies `!sortColumn.isEmpty()`

2021-06-18 22:35 UTC, kaliang1 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +      } else if (dataSchema.getDereferencedType() == DataSchema.Type.ARRAY) {
Sorry for the confusion, we should not be sorting over an array, I will fix this.

2021-06-22 16:41 UTC, jywadhwani commented on restli-resources/src/main/java/com/linkedin/metadata/restli/BaseEntityResource.java
> +      @QueryParam(PARAM_COUNT) int count) {
Can we use a default value of 10 for the count? you can do this by specifying `@Optional("10")`.

2021-06-23 15:39 UTC, jywadhwani commented
> I don't think they can be merged because it is used by clients, but I deprecated it [here](https://github.com/linkedin/datahub-gma/pull/101/commits/4bec13eeebf69d29b6d74611273f234cd81fd02f).

That is correct. But more than internal, we need to be careful about our open source users. Making breaking changes can impact our (invisible) open source adopters.

2021-06-23 15:41 UTC, jywadhwani approved these changes

2021-06-23 17:25 UTC, keremsahin1 commented on restli-resources/src/main/java/com/linkedin/metadata/restli/RestliConstants.java
> +  public static final String FINDER_FILTER_SORT = "filterAndSort";
I don't think we need to use a different finder name here. Search also does sorting but we don't have a `searchAndSort` filter per se. Sorting param is already optional and it's obvious that this new finder is able to sort if that param is set. Also, other filter finder also does sorting but with a default order :)

And you already deprecate the other finder, so, it should be okay to use same finder name for both. Maybe, you can also put a note such that user should only implement one of the filter finders in their resource implementation.

2021-06-23 18:47 UTC, keremsahin1 approved these changes
Great job!

2021-06-23 18:48 UTC, merged