feat: Use optimistic locking for db updates in ebean dao
linkedin/datahub-gma pull request #107
Opened 2021-06-16 06:39 UTC by keremsahin1

Start using optimistic locking to prevent [lost updates](https://www.avaje.org/occ.html) in Ebean dao. The feature is flag guarded for now. After testing it in production, the plan is to make it the default behavior going forward.

## Checklist
- [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [X] Tests for the changes have been added/updated (if applicable)

2021-06-16 21:03 UTC, keremsahin1 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +        SqlUpdate update = _server.createSqlUpdate(updateQuery);
Thanks, done

2021-06-16 21:15 UTC, jywadhwani requested changes

2021-06-16 21:15 UTC, jywadhwani commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +        fail("This shouldn't have failed when optimistic locking is disabled");
it shouldn't have failed if `oldAuditStamp` was `null` as well? can we verify this condition as well?

2021-06-16 21:19 UTC, jywadhwani commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +        fail("This shouldn't have failed when optimistic locking is disabled");
If optimistic locking was _NOT_ enabled, then the aspect should have been updated successfully. Can we verify that as well?

2021-06-17 01:21 UTC, RealChrisL commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +          throw new OptimisticLockException();
Do you want to put messages/aspects in the OptimisticLockException to provide the details?

2021-06-17 17:50 UTC, keremsahin1 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +          throw new OptimisticLockException();
Thanks, done

2021-06-17 17:51 UTC, keremsahin1 commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +        fail("This shouldn't have failed when optimistic locking is disabled");
After some refactoring, I don't think this is relevant any more. Actually, your comment was a trigger for the refactor :)

2021-06-17 17:54 UTC, keremsahin1 commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +        fail("This shouldn't have failed when optimistic locking is disabled");
This wasn't the main motivation for this test, I only want to test if I got OptimisticLockingException here. Other than that, all tests in the DAO is executed for both optimistic locking is enabled and disabled.

2021-06-17 20:19 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  private static final String DEFAULT_COLUMN_FOR_OPTIMISTIC_LOCK = CREATED_ON_COLUMN;
Curious, could there be a scenario where the column for optimistic locking is different from `created_on` column? If so, should we expose a constructor to provision that?
This might be beyond the scope of this change, but maybe worth addressing in future?

2021-06-17 20:23 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  public void setUseOptimisticLocking(boolean useOptimisticLocking) {
nit: `setOptimisticLocking` should suffice? don't see `Use` adding any value here.

2021-06-17 20:25 UTC, keremsahin1 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  private static final String DEFAULT_COLUMN_FOR_OPTIMISTIC_LOCK = CREATED_ON_COLUMN;
That's a good question. Considering the columns in the DB schema, there is no other column that can be meaningfully used for optimistic locking. `createdOn` is the only one that makes sense.

I guess I wanted to make this as generic as possible if we add a column to the DB schema which is used solely for optimistic locking. But, in that case, I guess using `@version` would be better rather than manually writing our own optimistic locking logic.

2021-06-17 20:35 UTC, keremsahin1 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  public void setUseOptimisticLocking(boolean useOptimisticLocking) {
I guess `setOptimisticLocking` doesn't make sense because this is a setter for the `useOptimisticLocking` class variable. If you also mean class variable should be renamed as `optimisticLocking`, I don't agree with that. But, I can replace `use` with `enable`, if that makes better sense?

2021-06-17 22:35 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  public void setUseOptimisticLocking(boolean useOptimisticLocking) {
Sure, let's stick with the current naming.

2021-06-17 22:45 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    if (insert) {
don't see a case (atleast in this PR) where `saveWithOptimisticLocking` is being called with `true` as `insert` variable. Is that intentional?

2021-06-17 22:45 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    final SqlUpdate update = _server.createSqlUpdate(updateQuery);
curious, why did you choose `createSqlUpdate` method over the `update` method of `EbeanServer`?

2021-06-18 03:48 UTC, keremsahin1 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    final SqlUpdate update = _server.createSqlUpdate(updateQuery);
`update` takes bean object directly and creates the sql query under the hood but the query it creates is different. It doesn't do optimistic locking. If you want it to do optimistic locking, you need to put `@version` annotation on the `createdOn` column in the bean model. But, we can't use it because of the reasons listed.

2021-06-18 03:49 UTC, keremsahin1 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    if (insert) {
That's true, it's not used right now but this method will be the default going forward after it's vetted. So, it'll be used :)

2021-06-18 18:04 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    final SqlUpdate update = _server.createSqlUpdate(updateQuery);
Sure. Using raw SQL query is fine but in certain cases it is better to use the bean object so that the query works for a wide range of databases.

2021-06-18 18:06 UTC, jywadhwani approved these changes

2021-06-18 18:06 UTC, merged

2021-06-18 18:13 UTC, keremsahin1 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    final SqlUpdate update = _server.createSqlUpdate(updateQuery);
Agreed, I also wouldn't prefer raw sql. I don't think there is really a way that I can make ebean generate the sql for me in this case (at least I'm not aware). That being said, this sql query should still be `ansi sql` compliant and I think it's supposedly work for all rdbms.

The only difference compared to the auto-generated query without optimistic locking is the adding of last condition ` and createdOn = :oldTimestamp`.