feat: add offset pagination to SCSI
linkedin/datahub-gma pull request #110
Opened 2021-06-24 14:27 UTC by kaliang1

This change adds offset pagination to SCSI. A new listUrns function returns a ListResult with pagination information. 

The next step is to add a filter method for offset pagination in BaseEntityResource, which will be done in a separate PR.

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2021-06-25 23:46 UTC, jywadhwani requested changes

2021-06-25 23:46 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    if (!isLocalSecondaryIndexEnabled()) {
this isn't checking the validity on index criterion array. Let's move it out of this method?

2021-06-25 23:46 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
>      final StringBuilder whereClause = new StringBuilder("WHERE t0.urn > ?");
If we choose to go with offset based pagination then this is not needed? it essentially sets the last urn which is needed in cursor based pagination

2021-06-25 23:46 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    final String limitClause = offsetPagination ?  "" : "LIMIT ?";
not sure about this. whether it is offset or cursor based pagination, we will need to limit the results, right?

2021-06-25 23:46 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
>      indexQuery.setParameter(1, lastUrn);
we shouldn't really be setting the last urn (even if it is empty string) for offset based pagination.

2021-06-28 14:18 UTC, kaliang1 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    final String limitClause = offsetPagination ?  "" : "LIMIT ?";
yes, we still need to limit the results. I did it [here](https://github.com/linkedin/datahub-gma/pull/110/files#diff-b5517a7dd054ca33f211c1dddc406b0bebbb4ae5a30cca17c59bff073b221488R1150) because to use `findPagedList()`, the `maxRows` had to be specified.

2021-07-13 17:30 UTC, jywadhwani commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +      @Nullable IndexSortCriterion indexSortCriterion, @Nonnull int start, int pageSize);
you do not need `Nonnull` with int type

2021-07-13 17:30 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    int pos;
you could simply initialize pos=1 (as default) and get rid of else?

2021-07-13 17:30 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +
can we load the total row count in background thread like https://ebean.io/docs/query/findPagedList

2021-07-13 19:53 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    pagedList.loadCount();
should we load it before retrieving the list of urns (i.e. before line 1177)?

2021-07-13 21:30 UTC, jywadhwani commented on dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java
> +      return null;
isn't the return type `Nonnull` in the base class that we are overriding? can we return an empty list here instead?

2021-07-13 21:54 UTC, jywadhwani approved these changes

2021-07-13 22:09 UTC, merged