feat: add aggregation count to SCSI
linkedin/datahub-gma pull request #115
Opened 2021-07-13 16:45 UTC by kaliang1

This change adds a new method to the DAO and resource to count aggregations. The aspect and path to be grouped/aggregated on can be passed in, and the count of the urns for each grouped value is returned. The returned value is a map of the field value to the count.

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2021-07-21 17:41 UTC, jywadhwani requested changes

2021-07-21 17:41 UTC, jywadhwani commented on dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java
> +    public Map<String, Long> countAggregate(@Nonnull IndexFilter indexFilter, @Nonnull IndexGroupByCriterion groupCriterion) {
The original method this is overriding seems to be returning `NonNull` value. Let's return an empty map here instead?

2021-07-21 17:41 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +      } else {
Let us explicitly check for the `getLongVal` to be non-null. That way if in future we add new columns then this code does not break.

2021-07-21 17:50 UTC, jywadhwani commented on dao-api/src/main/pegasus/com/linkedin/metadata/query/IndexGroupByCriterion.pdl
> +  path: string
should this be optional? Do you foresee a case where we may want to group by just the aspect name?

2021-07-21 17:55 UTC, jywadhwani commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +      @Nonnull IndexGroupByCriterion indexGroupByCriterion);
While running SQL query, we can group by multiple columns. This method has provision for grouping only one such column? Do you think we should extend this to multiple columns?

2021-07-21 18:02 UTC, jywadhwani commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +    IndexGroupByCriterion indexGroupByCriterion1 = new IndexGroupByCriterion().setAspect(AspectFoo.class.getCanonicalName())
let us also test the case when `IndexGroupByCriterion` uses an aspect and path that none of the filtered results contain?

2021-07-21 18:05 UTC, jywadhwani commented on dao-api/src/main/pegasus/com/linkedin/metadata/query/IndexGroupByCriterion.pdl
> +  path: string
Something like: there are 10 filtered results that satisfy `IndexFilter` condition, `aspectA` exists in 8 of them, `aspectB` in 5 of them, etc.

2021-07-21 19:07 UTC, kaliang1 commented on dao-api/src/main/pegasus/com/linkedin/metadata/query/IndexGroupByCriterion.pdl
> +  path: string
I think this could potentially be a use case in the future? To group by aspects, perhaps the path can be optional and for the aspects string, we could pass in "*" to indicate that we want to group by all of the aspects. What do you think?

2021-07-21 19:19 UTC, kaliang1 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +      @Nonnull IndexGroupByCriterion indexGroupByCriterion);
Sure, I think this could be a use case in the future.

2021-07-21 19:49 UTC, kaliang1 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +      @Nonnull IndexGroupByCriterion indexGroupByCriterion);
Actually, I'm not sure about how this would look like. For grouping by multiple columns, would that return the count of columns that have the same value for multiple columns? For example, if we group by X, Y, this would put aspects with the same values for both X and Y in one group and return the count?
Also, the returned value may be a nested map, which could get complicated with multiple group by conditions?

2021-07-22 17:39 UTC, jywadhwani commented on dao-api/src/main/pegasus/com/linkedin/metadata/query/IndexGroupByCriterion.pdl
> +  path: string
We could as well have a `Nullable` `IndexGroupByCriterion`? where null value would mean what you are suggesting?

2021-07-22 17:40 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  static <ASPECT extends RecordTemplate> String getFieldColumn(@Nonnull String stringPath,
nit: I would just name these variables as `path` and `aspect` (`string` as prefix doesn't add much value, I think)

2021-07-22 18:21 UTC, kaliang1 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  static <ASPECT extends RecordTemplate> String getFieldColumn(@Nonnull String stringPath,
For https://github.com/linkedin/datahub-gma/pull/115/files#diff-b5517a7dd054ca33f211c1dddc406b0bebbb4ae5a30cca17c59bff073b221488R989, it uses the variable `aspect` and I think `stringAspect` helps to differentiate them?

2021-07-22 18:27 UTC, jywadhwani commented on dao-api/src/main/pegasus/com/linkedin/metadata/query/IndexGroupByCriterion.pdl
> +  path: string
Let's just skip it for now. We can implement it later. This thread will help with tracking.

2021-07-22 18:29 UTC, jywadhwani commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +      @Nonnull IndexGroupByCriterion indexGroupByCriterion);
Sounds good. Let us skip this functionality for now.

2021-07-22 18:32 UTC, jywadhwani commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  static <ASPECT extends RecordTemplate> String getFieldColumn(@Nonnull String stringPath,
how about we use `aspectName` then?

2021-07-22 21:20 UTC, jywadhwani approved these changes

2021-07-22 21:20 UTC, merged