feat: add support for sub fields in ES Browse query
linkedin/datahub-gma pull request #119
Opened 2021-07-27 05:31 UTC by shreybatra

This is add support for filtering on subfield, which may have a different analyzer.
For example - filter `browsePaths.edge_search = value` will now be possible as
`browsePaths` is available in model but not `browsePaths.edge_search`.

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2021-07-27 16:55 UTC, jywadhwani commented on dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/browse/ESBrowseDAO.java
> +      if (_config.hasFieldInSchema(fieldParts[0])) {
any way we can add tests for this?

2021-07-27 16:58 UTC, jywadhwani commented on dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/browse/ESBrowseDAO.java
> +      if (_config.hasFieldInSchema(fieldParts[0])) {
also this restricts to one subfield? what if we have multiple?

2021-07-27 17:02 UTC, shreybatra commented on dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/browse/ESBrowseDAO.java
> +      if (_config.hasFieldInSchema(fieldParts[0])) {
This does not restrict to any number, we can have a long string, but the root field would only be present in the schema config right? So as long as `parts[0]` is present, it should work.

I will check for tests, there is none already present for it.

2021-07-27 19:13 UTC, shreybatra commented on dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/browse/ESBrowseDAO.java
> +      if (_config.hasFieldInSchema(fieldParts[0])) {
Added the testcases @jywadhwani .

2021-07-29 17:05 UTC, jywadhwani requested changes

2021-07-29 17:05 UTC, jywadhwani commented on dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/browse/ESBrowseDAO.java
> +      if (_config.hasFieldInSchema(fieldParts[0])) {
Thanks for adding the test case. 

I am not clear how user friendly the interface is.
Are you suggesting that the client (like DataHub app) should be aware of the subfields that exist in search index and pass them in the request map as input?

2021-08-11 17:35 UTC, jywadhwani commented
Do we still need this PR?

2021-08-11 18:25 UTC, shreybatra commented
I don't think so, let me close this.! Thanks

2021-08-11 18:25 UTC, closed without merging