rfc: Elasticsearch Integration Testing
linkedin/datahub-gma pull request #15
Opened 2020-10-19 21:51 UTC by jplaisted

Brief: Design an easy to use test framework for integration testing Elasticsearch with GMA.

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2020-10-19 21:52 UTC, jplaisted commented
Rendered at https://github.com/jplaisted/datahub-gma/blob/integRfc/docs/rfc/active/elasticsearch-integration-testing.md

2020-10-21 23:33 UTC, camelliazhang commented
A general comment: do you want to mention/try some existing integration plugins? 
https://sharing.luminis.eu/blog/elasticsearch-instances-for-integration-testing/

2020-10-22 04:33 UTC, mars-lan requested changes
Some minor comments. Otherwise LGTM

2020-10-22 04:33 UTC, mars-lan commented on docs/rfc/active/elasticsearch-integration-testing.md
> +- Must be able to easily start an Elasticsearch instance for testing at test start up, and then clean it up at test tear
Will the startup/teardown be at the per-test or per-class granularity?

2020-10-22 04:33 UTC, mars-lan commented on docs/rfc/active/elasticsearch-integration-testing.md
> +1. `dao-impl/elasticsearch-dao-integ-testing`: Contains JUnit 5 extension and interfaces, as well as assertj assertions.
Maybe create a top-level folders to hold all test-related modules, e.g. test models, integ test harness, test utils etc?

2020-10-22 04:33 UTC, mars-lan commented on docs/rfc/active/elasticsearch-integration-testing.md
> +- **Works only with Elasticsearch 5.** This is the biggest drawback here. This design has not considered an
If we expect the lib to take a hard dependency on ES 5, maybe we should name the module as such for clarity?

2020-10-22 21:54 UTC, jplaisted commented
> A general comment: do you want to mention/try some existing integration plugins?
> https://sharing.luminis.eu/blog/elasticsearch-instances-for-integration-testing/

See the RFC. It does mention why we're building something of a custom framework here.

A) Not everyone is going to be able to use the same solution (e.g. we can't use docker at LinkedIn). Some abstraction here is needed.
B) There's more to the setup than just starting/stopping ES. There's also connecting to it, making an index, setting settings/mappings, making DAOs, etc.

The RFC also mentions it will use Testcontainers under the hood by default.

2020-10-22 21:54 UTC, jplaisted commented on docs/rfc/active/elasticsearch-integration-testing.md
> +- Must be able to easily start an Elasticsearch instance for testing at test start up, and then clean it up at test tear
I think we can have both. Easily specified by making a `SearchIndex` static or non-static :)

2020-10-22 21:55 UTC, jplaisted commented on docs/rfc/active/elasticsearch-integration-testing.md
> +1. `dao-impl/elasticsearch-dao-integ-testing`: Contains JUnit 5 extension and interfaces, as well as assertj assertions.
SG. So

```
testing/
  test-models/
  elasticsearch-dao-integ-testing/
  elasticsearch-dao-integ-testing-docker/
```

? Moving `test-models`?

2020-10-22 21:56 UTC, jplaisted commented on docs/rfc/active/elasticsearch-integration-testing.md
> +- **Works only with Elasticsearch 5.** This is the biggest drawback here. This design has not considered an
We didn't with our other libraries. Probably better to be consistent. So lack of number means 5, in the future we'll probably have modules with 7 in their name...

2020-10-23 03:24 UTC, mars-lan commented on docs/rfc/active/elasticsearch-integration-testing.md
> +- Must be able to easily start an Elasticsearch instance for testing at test start up, and then clean it up at test tear
I'm more concerned about the overhead of starting/stopping ES instances if it's done at a per-test level.

2020-10-23 03:24 UTC, mars-lan commented on docs/rfc/active/elasticsearch-integration-testing.md
> +1. `dao-impl/elasticsearch-dao-integ-testing`: Contains JUnit 5 extension and interfaces, as well as assertj assertions.
LGTM

2020-10-23 03:25 UTC, mars-lan commented on docs/rfc/active/elasticsearch-integration-testing.md
> +- **Works only with Elasticsearch 5.** This is the biggest drawback here. This design has not considered an
The bigger question is can we somehow make the test harness ES version insensitive?

2020-10-23 17:53 UTC, jplaisted commented on docs/rfc/active/elasticsearch-integration-testing.md
> +- Must be able to easily start an Elasticsearch instance for testing at test start up, and then clean it up at test tear
Oh, ah. I meant index life cycle can be per test or class by setting the field(s) as static/instance.

The cluster itself should have a long lived life cycle, ideally. Across all tests. Yes.

2020-10-23 18:00 UTC, jywadhwani commented on docs/rfc/active/elasticsearch-integration-testing.md
> +- **Works only with Elasticsearch 5.** This is the biggest drawback here. This design has not considered an
+1 our tests should (ideally) be independent of the ES version. Atleast the generic tests (ES version insensitive) should reside in one place?

2020-10-23 18:46 UTC, jplaisted commented on docs/rfc/active/elasticsearch-integration-testing.md
> +- **Works only with Elasticsearch 5.** This is the biggest drawback here. This design has not considered an
Changing the version that is started with docker/test containers is super simple, just involves changing a string.

The issue is the test framework here is also going to be connecting to it, and making DAOs, both of which link against the ES client (directly or transitively). So we have a tight coupling, like it or not. Even if we didn't have a coupling directly, we've have it transitively because of how the DAO is written today.

We'll be encountering the same issues when we migrate the DAO to 7.

2020-10-23 18:52 UTC, mars-lan commented on docs/rfc/active/elasticsearch-integration-testing.md
> +- Must be able to easily start an Elasticsearch instance for testing at test start up, and then clean it up at test tear
SGTM

2020-10-23 18:55 UTC, mars-lan commented on docs/rfc.md
> +# GMA RFC
Move this to a separate PR? No review needed.

2020-10-23 18:55 UTC, mars-lan commented on docs/rfc.md
> +# GMA RFC
And all the cleanup of existing RFCs

2020-10-23 20:09 UTC, mars-lan requested changes
Still got some extraneous files?

2020-10-23 21:09 UTC, jplaisted commented
> Still got some extraneous files?

Done

2020-10-23 21:13 UTC, mars-lan commented on docs/rfc/active/15-elasticsearch-integration-testing/README.md
> +1. `dao-impl/elasticsearch-dao-integ-testing`: Contains JUnit 5 extension and interfaces, as well as assertj assertions.
Please update the module paths

2020-10-23 21:36 UTC, mars-lan approved these changes

2020-10-23 23:23 UTC, jywadhwani commented on docs/rfc/active/15-elasticsearch-integration-testing/README.md
> +## Requirements
I believe testing `browse` feature which is also dependent on search stack is not in the scope of this doc?

2020-10-23 23:41 UTC, jywadhwani commented on docs/rfc/active/15-elasticsearch-integration-testing/README.md
> +  Colleciton<BulkRequest> getAllRequests();
nit: you mean `Collection`? same for the line below.

2020-10-24 00:01 UTC, jywadhwani commented on docs/rfc/active/15-elasticsearch-integration-testing/README.md
> +    .usingConfig(config)
I assume the search query template will be pulled from the search config and this assertion will test that feature. How about autocomplete? Also we provide facet fields in the search config primarily used for aggregations and those fields require certain types/params (https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html). Do we provide assertion helpers for them as well?

2020-10-26 20:37 UTC, jplaisted commented on docs/rfc/active/15-elasticsearch-integration-testing/README.md
> +## Requirements
Correct. We can always add on later. For now, I'm looking just to test `ESSearchDAO`. We can consider browse DAO later.

2020-10-26 20:38 UTC, jplaisted commented on docs/rfc/active/15-elasticsearch-integration-testing/README.md
> +
That's just naturally part of test set up / tear down, I guess? Maybe adding it to the "sanity" tests later would be a good idea.

2020-10-26 20:39 UTC, jplaisted commented on docs/rfc/active/15-elasticsearch-integration-testing/README.md
> +    .usingConfig(config)
Presumably, this isn't mean to be exhaustive.

2020-10-27 17:15 UTC, merged