(feat):Create EBeanLocalAccess to support data access on new schema
linkedin/datahub-gma pull request #171
Opened 2022-05-31 18:55 UTC by yangyangv2

## Checklist

- [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [X] Links to related issues [META-16566](https://jira01.corp.linkedin.com:8443/browse/META-16566) (LI Internal)
- [ ] Tests for the changes have been added/updated (if applicable)
- [X] Docs related to the changes have been added/updated [New Schema Migration](https://docs.google.com/document/d/12eqBOHgqsLxR0RIRwXo4ilh39pmoNQ9XZHk6S81XXeU/edit)

2022-06-03 21:44 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EBeanLocalAccess.java
> +  public  List<URN> listUrns(@Nonnull IndexFilter indexFilter,
Do we need these listUrns methods? If I'm not mistaken, they are related to SCSI only.

2022-06-08 01:31 UTC, jsdonn requested changes
Lots of small things, but I think overall looks great Yang! I was expecting a big mess from the construction of the SQL queries, but it was cleaner than expected. Good javadocs too. Let me know if you have any questions about some of my comments.

As a reminder, 3 methods should be added in phase 2:
public boolean exists(@Nonnull URN urn)

public Map<String, Long> countAggregate(@Nonnull IndexFilter indexFilter,
@Nonnull IndexGroupByCriterion indexGroupByCriterion)

public <ASPECT extends RecordTemplate> ListResult<URN> listUrns(@Nonnull Class<ASPECT> aspectClass, int start,int pageSize)

Thanks!

2022-06-08 01:31 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EBeanLocalAccess.java
> +            String.format("Row count is more than total count: %d / %d", sqlRows.size(), totalCount));
Would instead recommend:
"Row count (%d) is more than total count (%d)"

2022-06-08 01:31 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java
> +    int numOfRecords = 100;
Can we move this into its own testing method? And check total return value of add() == 100.

2022-06-08 01:31 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java
> +    assertEquals(6, listUrns.getTotalPageCount());
Why is this 6 and not 5? Am I missing something? Lol
1 25-29
2 30-34
3 35-39
4 40-44
5 45-49

2022-06-08 01:31 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java
> +package com.linkedin.metadata.dao;
Can we add a few more tests? Especially for batchGetUnion and maybe toListResult?

2022-06-08 23:32 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/EBeanDAOUtils.java
> +  public static int ceilDiv(int x, int y) {
No, this method will fail with negatives. For example  -3 / -2: expect 2, but the above method will give 3. 

But thanks for calling out, added negative test case for the original method.

2022-06-08 23:40 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java
> +      throw new IllegalArgumentException("Aspect name is too long to be normalized: " + aspectCanonicalName);
Not I'm aware of. 

We can build complicated encoding logic to keep the columns are within certain length, but a more user friendly approach is to allow users to define alias by themselves on their GMS.

we can throw exception for now and add this logic later on.,

2022-06-08 23:50 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EBeanLocalAccess.java
> +            String.format("Row count is more than total count: %d / (%d - %d)", sqlRows.size(), totalCount, start));
I'd prefer to keep the "start" in the log message. I can change it to
String.format("Row count (%d) is more than total count of (%d) started from (%s)", sqlRows.size(), totalCount, start)

2022-06-09 00:03 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java
> +    int numOfRecords = 100;
it's a common setup for other query test cases. Good enough to serve the DB query cases. 

Putting DB setup into method level also means, each method needs to take care setup and withdraw, which could be less performant when test cases are many.

Common setup will not work in DB write cases, if we need these cases, we can create different test classes.

2022-06-09 00:08 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java
> +    assertEquals(6, listUrns.getTotalPageCount());
This is a bug. Good catch! Updated the test case

2022-06-09 00:15 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java
> +  public void testGetAspect() {
Can you also add a test for get when we want to get something that does not actually exist?

2022-06-09 00:17 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EBeanLocalAccess.java
> +            String.format("Row count is more than total count: %d / (%d - %d)", sqlRows.size(), totalCount, start));
Sounds good. Very nitpicky here but I think this makes a bit more sense:

String.format("Row count (%d) is more than total count of (%d), starting from (%s)", sqlRows.size(), totalCount, start)

2022-06-09 00:17 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java
> +package com.linkedin.metadata.dao;
Absolutely, feel free to add test cases in your mind. Will add more tests together with the phase-2 PR.  The current priority is to unblock the upstream execution.

2022-06-09 00:19 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java
> +package com.linkedin.metadata.dao;
Awesome. Let's worry about more thorough testing in phase 2 then.

2022-06-09 00:20 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EBeanLocalAccessTest.java
> +  public void testGetAspect() {
Let's address this in phase 2.

2022-06-09 00:20 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtilsTest.java
> +    assertEquals(sql, "WHERE\n" + "i_testing_aspectfoo$id < 12");
Let's address this in phase 2.

2022-06-09 00:21 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java
> +          + "on duplicate key update %s = :metadata;";
> Why use + and not just put the whole statement into the same string?

I see this is because of newline :) You can ignore this comment

2022-06-09 02:12 UTC, jsdonn reviewed
Just 2 small things and the rest should be good.

2022-06-09 02:12 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EBeanLocalAccess.java
> +    totalCount = sqlRows.get(0).getInteger("_total_count");
Let's address having good javadocs in phase 2.

2022-06-09 02:12 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EBeanLocalAccess.java
> +        totalPageCount = ceilDiv(totalCount, pageSize);
I think we can remove this line (213) right? @yangyangv2 since we have line 208 which does the same thing.

2022-06-09 02:12 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java
> +      throw new IllegalArgumentException("Aspect name is too long to be normalized: " + aspectCanonicalName);
Agreed, let's address this later down the line.

2022-06-09 02:12 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java
> +    aspectCanonicalName = trimColumnName(aspectCanonicalName);
Let's address the logic for this method (since it is not trivial) in phase 2.

2022-06-09 02:12 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLSchemaUtils.java
> +   * @return
Let's address javadocs next phase.

2022-06-09 02:12 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java
> +          + "on duplicate key update %s = :metadata;";
Can you capitalize the "on duplicate key update"? @yangyangv2

2022-06-09 03:53 UTC, jsdonn approved these changes
Thank you for addressing my comments!

2022-06-09 04:00 UTC, merged