feat: Add EbeanLocalRelationshipWriterDAO and BaseLocalRelationshipBu…
linkedin/datahub-gma pull request #186
Opened 2022-07-16 02:49 UTC by zhixuanjia

…ilder

Units are in next PR.

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2022-07-19 23:08 UTC, jsdonn requested changes
Mostly looks good, just some small things.

2022-07-19 23:08 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java
> +  private <RELATIONSHIP extends RecordTemplate> void processRemoveOption(String tableName, RELATIONSHIP relationship,
nit: processRemovalOption

2022-07-19 23:08 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java
> +    if (removalOption == RemovalOption.REMOVE_ALL_EDGES_FROM_SOURCE_TO_DESTINATION) {
switch/case?

2022-07-25 20:18 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java
> +  private static final String DELETE_BY_SOURCE_AND_DESTINATION = "DELETE FROM %s WHERE destination = :destination ADN source = :source";
fixed.

2022-07-25 20:18 UTC, zhixuanjia commented on dao-api/src/main/java/com/linkedin/metadata/dao/builder/BaseLocalRelationshipBuilder.java
> +  public class LocalRelationUpdates {
good catch, updated.

2022-07-25 20:19 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java
> +    if (removalOption == BaseGraphWriterDAO.RemovalOption.REMOVE_ALL_EDGES_FROM_SOURCE) {
I don't see a big difference so leave it as it is.

2022-07-25 20:24 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/MysqlDevInstance.java
> +package com.linkedin.metadata.dao;
Sure, moved it to the utils folder.

2022-07-25 20:33 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipWriterDAOTest.java
> +    _server.execute(Ebean.createSqlUpdate("delete from metadata_relationship_belongsto"));
yes, truncate works here too.

2022-07-25 20:34 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java
> +    if (removalOption == RemovalOption.REMOVE_ALL_EDGES_FROM_SOURCE_TO_DESTINATION) {
I don't see a big difference so leave it as it is.

2022-07-25 20:34 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipWriterDAO.java
> +  private <RELATIONSHIP extends RecordTemplate> void processRemoveOption(String tableName, RELATIONSHIP relationship,
updated

2022-07-26 19:11 UTC, jsdonn commented
LGTM

2022-07-26 19:11 UTC, jsdonn approved these changes

2022-07-26 19:11 UTC, merged