feat: Integrate local relationship writer DAO
linkedin/datahub-gma pull request #205
Opened 2022-08-22 20:52 UTC by zhixuanjia

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2022-08-23 01:15 UTC, jsdonn requested changes

2022-08-23 01:15 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
> +    AspectFooBar aspectFooBar = new AspectFooBar().setBars(new BarUrnArray(new BarUrnArray(barUrn1, barUrn2, barUrn3)));
is this supposed to be two of the same constructor (new BarUrnArray(new BarUrnArray))

2022-08-23 01:15 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
> +        BarSnapshot.class, new Filter().setCriteria(new CriterionArray()),
nit: we can make a static "EMPTY_FILTER" variable?

2022-08-23 01:15 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
> +    _server.createSqlUpdate("DROP TABLE metadata_entity_foo").execute();
maybe we need to add "IF EXISTS" here just in case?

2022-08-23 23:31 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
> +    _server.createSqlUpdate("DROP TABLE metadata_entity_foo").execute();
"IF EXISTS" is left out on purpose. Test should fail if we can't drop the table.

2022-08-23 23:35 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
> +        BarSnapshot.class, new Filter().setCriteria(new CriterionArray()),
makes sense, updated

2022-08-23 23:36 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
> +    AspectFooBar aspectFooBar = new AspectFooBar().setBars(new BarUrnArray(new BarUrnArray(barUrn1, barUrn2, barUrn3)));
good catch, fixed

2022-08-24 16:18 UTC, jsdonn approved these changes
Thanks for addressing comments.

2022-08-24 16:18 UTC, merged