fix: [Schema Evolution] Support multiple version tables and set basel…
linkedin/datahub-gma pull request #212
Opened 2022-09-07 00:51 UTC by zhixuanjia

…ine version

Changes verified using GMS local deployment.

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2022-09-07 22:36 UTC, jsdonn requested changes

2022-09-07 22:36 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManager.java
> +    boolean disableClean = !configProp.containsKey(DISABLE_CLEAN) || Boolean.parseBoolean(configProp.getProperty(DISABLE_CLEAN));
Why don't we just always set this disableClean to true? Any use case for clean?

2022-09-07 22:36 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManager.java
> +
very nit: unnecessary line

2022-09-07 22:36 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManager.java
> +    //This is especially useful for production environments where running clean can be quite a career limiting move.
lol

2022-09-07 22:36 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManagerTest.java
> +    _server.createSqlUpdate("DROP TABLE  my_version_table").execute();
very nit: extra space between TABLE and my_version_table

2022-09-08 16:58 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManager.java
> +    boolean disableClean = !configProp.containsKey(DISABLE_CLEAN) || Boolean.parseBoolean(configProp.getProperty(DISABLE_CLEAN));
Clean is useful when we want to have a fresh db to start with, specially when running unit tests. We'll keep this as internal config and not mention it on the onboarding doc.

2022-09-08 17:02 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManager.java
> +
deleted.

2022-09-08 17:27 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/FlywaySchemaEvolutionManager.java
> +    boolean disableClean = !configProp.containsKey(DISABLE_CLEAN) || Boolean.parseBoolean(configProp.getProperty(DISABLE_CLEAN));
Sounds good to me.

2022-09-08 17:29 UTC, jsdonn approved these changes
LGTM. will review onboarding steps later.

2022-09-08 17:29 UTC, merged