Support filter on array value for new schema
linkedin/datahub-gma pull request #221
Opened 2022-11-23 06:12 UTC by zhixuanjia

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2022-11-23 19:02 UTC, jsdonn requested changes

2022-11-28 22:39 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java
> +        return String.format("JSON_SEARCH(%s, 'one', '%s') IS NOT NULL", indexColumn, parseIndexValue(indexValue));
What user provides when `IN` being used is an array. For example, user provide array value ["foo", "bar"] in `where i_column$field IN ("foo", "bar")`; 

What user provides when `CONTAIN` being used is a single value. For example, user provide value "foo" in `where JSON_SEARCH(i_column$field, 'one', 'foo')`;

2022-11-28 22:41 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +  public void testNewSchemaFilerByArray() {
fixed.

2022-11-30 00:06 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java
> +        return String.format("JSON_SEARCH(%s, 'one', '%s') IS NOT NULL", indexColumn, parseIndexValue(indexValue));
Right, I had a brain fart, thanks for the clarification.

2022-12-02 02:00 UTC, jsdonn requested changes

2022-12-02 02:00 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java
> +      final String aspect = indexCriterion.getAspect(GetMode.NULL);
no need for GetMode.NULL. `aspect` is a required field in IndexCriterion.pdl.

2022-12-02 02:00 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java
> +      if (aspect != null && !isUrn(aspect)) {
no need for `aspect != null`

2022-12-02 17:25 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    if (_schemaConfig == SchemaConfig.OLD_SCHEMA_ONLY && !isLocalSecondaryIndexEnabled()) {
so when user choose NEW_SCHEMA_ONLY mode, we don't expect user to enable SCSI because there is no need for it. We should only check if SCSI is enabled when user to choose OLD_SCHEMA_ONLY mode.

2022-12-02 17:35 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java
> +      final String aspect = indexCriterion.getAspect(GetMode.NULL);
right, I think we should throw RequiredFieldNotPresentException if user did not set this field. Updated.

2022-12-02 17:39 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLIndexFilterUtils.java
> +      if (aspect != null && !isUrn(aspect)) {
updated.

2022-12-02 17:40 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +      // Create index filter with value ["bar", "foo", "baz"]. Order is different.
Yes, policy catalog has a use case requires exact match, including ordering.

2022-12-02 17:44 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    if (_schemaConfig == SchemaConfig.OLD_SCHEMA_ONLY && !isLocalSecondaryIndexEnabled()) {
I agree with updating other places. Will make the change.

2022-12-02 19:08 UTC, jsdonn approved these changes
LGTM

2022-12-02 19:09 UTC, merged