feat(new schema): Redesign local relationship query filter
linkedin/datahub-gma pull request #227
Opened 2022-12-21 01:31 UTC by zhixuanjia

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2022-12-21 01:58 UTC, jsdonn reviewed
Could you please share some context on why you are refactoring the class to not extend BaseQueryDAO?

2022-12-21 02:23 UTC, jsdonn requested changes

2022-12-21 02:23 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java
> +          orClauses.add(entry.getKey() + supportedCondition.get(pair.getValue0()) + "'" + parseLocalRelationshipValue(pair.getValue1()) + "'");
What about CONTAIN? Is that supported by local relationship filter? Do you need to add a special case for CONTAIN?

2022-12-21 02:23 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java
> +    tablePrefix = tablePrefix == null ? "" : tablePrefix + ".";
Is there a case where tablePrefix can be ""?

2022-12-21 02:23 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
> +    LocalRelationshipCriterion filterCrtierion = new LocalRelationshipCriterion()
nit: typo - filterCriterion

2022-12-21 02:23 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
> +    LocalRelationshipCriterion filterCrtierion = new LocalRelationshipCriterion()
nit: typo - filterCriterion

2022-12-21 02:23 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
> +    LocalRelationshipCriterion filterCrtierion = new LocalRelationshipCriterion()
nit: typo

2022-12-21 02:23 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
> +    LocalRelationshipCriterion filterCrtierion = new LocalRelationshipCriterion()
nit: typo

2022-12-21 02:23 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
> +    LocalRelationshipCriterion filterCrtierion2 = new LocalRelationshipCriterion()
nit: typo

2022-12-21 02:23 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
> +    LocalRelationshipCriterion filterCrtierion = new LocalRelationshipCriterion()
nit: typo

2022-12-21 02:23 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
> +  public void testFindOneEntityWithInCondition() throws URISyntaxException {
want to add a test case for opposite? aka no entities match the IN filter

2022-12-21 02:24 UTC, jsdonn commented on dao-api/src/main/pegasus/com/linkedin/metadata/query/UrnField.pdl
> +record UrnField {
So are all of these *Field models going to be general or will users need to onboard their specific use cases?

2022-12-28 05:24 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java
> +          orClauses.add(entry.getKey() + supportedCondition.get(pair.getValue0()) + "'" + parseLocalRelationshipValue(pair.getValue1()) + "'");
So CONTAINS is not supported for now. https://github.com/linkedin/datahub-gma/blob/master/dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java#L48

But if we support it in the future, we will revisit this part of code.

2022-12-28 05:29 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/SQLStatementUtils.java
> +    tablePrefix = tablePrefix == null ? "" : tablePrefix + ".";
If there is only one table involved in the SQL query, then table prefix is not needed. For example, the findEntities api https://github.com/linkedin/datahub-gma/blob/master/dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java#L48 only needs to query one entity table so no need to have table prefix.

2022-12-28 05:31 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
> +    LocalRelationshipCriterion filterCrtierion = new LocalRelationshipCriterion()
updated.

2022-12-28 05:31 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
> +    LocalRelationshipCriterion filterCrtierion = new LocalRelationshipCriterion()
updated

2022-12-28 05:31 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
> +    LocalRelationshipCriterion filterCrtierion = new LocalRelationshipCriterion()
updated

2022-12-28 05:31 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
> +    LocalRelationshipCriterion filterCrtierion = new LocalRelationshipCriterion()
updated

2022-12-28 05:31 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
> +    LocalRelationshipCriterion filterCrtierion2 = new LocalRelationshipCriterion()
updated

2022-12-28 05:31 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
> +    LocalRelationshipCriterion filterCrtierion = new LocalRelationshipCriterion()
updated

2022-12-28 05:32 UTC, zhixuanjia commented on dao-api/src/main/pegasus/com/linkedin/metadata/query/UrnField.pdl
> +record UrnField {
So I wrote a doc to explain why we have these *Field. https://docs.google.com/document/d/1U77W5OeubBvSZPkhouMLD7Q99vwsGoUmH9iri12v_GQ/edit#

2022-12-28 05:37 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
> +  public void testFindOneEntityWithInCondition() throws URISyntaxException {
sure, added a test for no match case

2022-12-28 05:58 UTC, zhixuanjia commented
This PR has two main purposes. 1. Properly support IN condition. 2. Replace the Filter with LocalRelationshipFilter. The Filter used in BaseQueryDAO only has minimal capability. For example, the only value type it supports is string and user can only pass in string as field as well.

2023-01-03 22:30 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java
>      if (filter.getDirection() == RelationshipDirection.$UNKNOWN) {
Why is the relationship direction included in the relationship filter? What happens if we use an empty filter when querying? I didn't see a test case for that.

2023-01-03 22:54 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java
>      if (filter.getDirection() == RelationshipDirection.$UNKNOWN) {
So the direction in the relationship filter is used to [generate the SQL](https://github.com/linkedin/datahub-gma/blob/0d89f5f62187959ce8884d02b0d93417853a4a3e/dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/utils/MultiHopsTraversalSqlGenerator.java#L47) for querying relationships.

2023-01-03 22:58 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java
>      if (filter.getDirection() == RelationshipDirection.$UNKNOWN) {
It is also used to determine [what should be returned](https://github.com/linkedin/datahub-gma/blob/master/dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java#L108).

2023-01-03 23:06 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java
>      if (filter.getDirection() == RelationshipDirection.$UNKNOWN) {
Cool, thanks for sharing. Could you also add a test case where you use the EMPTY_FILTER?

2023-01-04 00:22 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java
>      if (filter.getDirection() == RelationshipDirection.$UNKNOWN) {
Sure, added a test case: `testFindEntitiesWithEmptyRelationshipFilter`

2023-01-04 00:27 UTC, jsdonn approved these changes

2023-01-04 00:27 UTC, merged