Add direct SQL execution pathway for job-gms record retrieval
linkedin/datahub-gma pull request #252
Opened 2023-05-09 17:47 UTC by jphui

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2023-05-10 16:55 UTC, ibuenros commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +      query.setParameter("aspect", aspectClass.getCanonicalName());
should you be using `ModelUtils.getAspectName` as above?

2023-05-10 16:55 UTC, ibuenros commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    _directSqlRetrieval = gmsName.toLowerCase().equals("job-gms");
This seems hacky. Can't we just configure on a per-job basis? Or Lix it (understand this requires more code, so not necessary)?

2023-05-10 18:20 UTC, jphui commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +      query.setParameter("aspect", aspectClass.getCanonicalName());
It does the same thing, but yes I agree for consistency it's worth making the change:
```
  public static <T extends DataTemplate> String getAspectName(@Nonnull Class<T> aspectClass) {
    return aspectClass.getCanonicalName();
  }
```

2023-05-10 18:22 UTC, jphui commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    _directSqlRetrieval = gmsName.toLowerCase().equals("job-gms");
> configure on a per-job basis
Right, so the idea is that `job-gms` will [call this constructor](https://jarvis.corp.linkedin.com/codesearch/result/?name=BaseLocalDaoFactory.java&path=job-gms%2Fjob-factories%2Fsrc%2Fmain%2Fjava%2Fcom%2Flinkedin%2Fdatajob%2Ffactories%2Fdao&reponame=multiproduct%2Fjob-gms#126) and activate the flag.

Is there a better way to recognize "who" is the caller... just rattling some alternate ideas maybe adding a public method to EbeanLocalDAO that can "trigger" the flag manually? Might be a safer and less hacky way :)

2023-05-11 18:13 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    }
Under what condition, we choose this instead of direct sql retrieval?

2023-05-11 18:21 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  public void useDirectSqlQuery() {
I would suggest we add some documentation why have feature, maybe mention GCN ticket, google doc. This confuse new comers (future team members) why we have this method.

2023-05-11 21:12 UTC, jphui commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  public void useDirectSqlQuery() {
Ok sounds good! I'll add descriptions here as well!

2023-05-15 20:42 UTC, jsdonn requested changes

2023-05-15 20:42 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    if (_ebeanFindBuilder) {
What's the difference between this _server.find() method and the original one (line 426)?

2023-05-15 20:42 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +    ORIGINAL,
nit: original doesn't mean anything to people that don't have the previous context. can we rename this to something more meaningful?

2023-05-15 20:43 UTC, jsdonn commented
Can you also add some description to the PR? :) It will help with context for reviewers that aren't looped in on the original issue.

2023-05-15 20:58 UTC, ibuenros commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    _directSqlRetrieval = gmsName.toLowerCase().equals("job-gms");
Why do you need to determine who is the caller? I see there's a cfg as input to the constructor, can't the job just configure which DAO it wants to use?

2023-05-15 21:19 UTC, zhixuanjia commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    }
Can we at least add a TODO for the second find method to clean it up? Future code reader will be confused on why we implemented 3 find in three different way...

2023-05-15 21:54 UTC, jphui commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    _directSqlRetrieval = gmsName.toLowerCase().equals("job-gms");
`ServerConfig` is part of the Ebean package and is meant to be used to configure the Server; it is not meant to be used for DAO configuration. See the updated way to set the flags; I got rid of this hacky way to do it and make it more explicit :)

2023-05-15 22:24 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    if (!_directSqlRetrieval && !_ebeanFindBuilder) {
Is this for experimental to have both? and you will only keep one SQL solution right?

2023-05-15 22:24 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    final PrimaryKey key = new PrimaryKey(urn.toString(), ModelUtils.getAspectName(aspectClass), 0L);
Is "key" used outside line 425? if not, please move it into the if-block.

2023-05-15 22:24 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +        dao.useDirectSqlQuery();
can we set FindMethodology directly to dao instead of operating on boolean flags?

2023-05-15 22:28 UTC, jphui commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    if (!_directSqlRetrieval && !_ebeanFindBuilder) {
The idea is that we keep whichever one works with a priority on the direct SQL execution in order to wean off of Ebean's hidden implementation details.

2023-05-15 22:30 UTC, jphui commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +        dao.useDirectSqlQuery();
> directly to dao

What does this mean? Is there a better way to accomplish this config?

2023-05-15 22:36 UTC, ibuenros commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  public void useEbeanFindBuild() {
Is there a default? What happens if the user calls neither useDirectSqlQuery nor useEvenaFindBuild?

2023-05-15 22:38 UTC, jphui commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    final PrimaryKey key = new PrimaryKey(urn.toString(), ModelUtils.getAspectName(aspectClass), 0L);
Moved in most recent commit, thanks for the suggestion

2023-05-15 22:41 UTC, jphui commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  public void useEbeanFindBuild() {
Both start as `false` and the first line in `queryLatest()` is the default: `if (!_directSqlRetrieval && !_ebeanFindBuilder)` --> use original retrieval mechanism...

Thoughts on maybe a better design to have the default at the "bottom" rather than having an if-clause at the beginning employ it?

2023-05-15 22:53 UTC, ibuenros commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  public void useEbeanFindBuild() {
Oh, so in total there are three options:legacy, "ebeanFindBuilder", and "directSqlRetrieval".  Just add clear documentation about this behavior. Each public method should be documented, and you can mention default behavior there.

2023-05-15 23:07 UTC, jphui commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  public void useEbeanFindBuild() {
> documented

Is something brief like

```
Raise flag to use direct SQL execution through Ebean's findNative() method during record insertion
By default, Ebean's find(Class, Object) is used, see GCN-38382
```

sufficient?

2023-05-15 23:28 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +        dao.useDirectSqlQuery();
I think Yang means similar to what we did for the new schema flags. Create an enum in EbeanLocalDAO class and operate on that instead of boolean flags. Although I feel that this is temporary work for now right? We will experiment with which method will resolve the issue first and then clean up the code after. So it shouldn't matter too much? Correct me if I'm wrong @jphui .

2023-05-16 04:31 UTC, jphui commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +        dao.useDirectSqlQuery();
Ah I see... Based off of @ibuenros 's feedback, is it more prudent to:

1. add a new constructor that sets this Enum
2. have a public method serve as a toggle (as it is currently implemented)

2023-05-16 20:09 UTC, jphui commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java
> +        dao.useDirectSqlQuery();
Did a quick look at the implementation for dual schema and am uploading a new PR with that approach.

2023-05-16 21:26 UTC, jphui commented
(Had to force push because was running into a `[remote rejected] ... (failure)` issue (no error message)

2023-05-16 21:40 UTC, ibuenros approved these changes

2023-05-16 22:01 UTC, jsdonn approved these changes

2023-05-16 22:13 UTC, merged