Spotless
linkedin/datahub-gma pull request #3
Opened 2020-09-30 23:13 UTC by jplaisted

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2020-10-05 14:18 UTC, mars-lan commented on .github/ISSUE_TEMPLATE/--bug-report.md
> +**Describe the bug** A clear and concise description of what the bug is.
Yeah it's a bit out of our control. Is it possible to tune the format so that it works in both cases?

2020-10-05 19:07 UTC, jplaisted commented on .github/ISSUE_TEMPLATE/--bug-report.md
> +**Describe the bug** A clear and concise description of what the bug is.
I don't think so. This is probably GitHub's fault for having two different renderers, one of which is non standard.

2020-10-05 19:08 UTC, jplaisted commented on .github/ISSUE_TEMPLATE/--bug-report.md
> +**Describe the bug** A clear and concise description of what the bug is.
The best solution is to probably just make these section headers instead. They don't have to be level one, we can use something like 3rd or 4th level headings `####` to make them a bit smaller.

# first
## second
### third
#### fourth

2020-10-05 20:17 UTC, mars-lan commented on .github/ISSUE_TEMPLATE/--bug-report.md
> +**Describe the bug** A clear and concise description of what the bug is.
SGTM

2020-10-05 22:28 UTC, mars-lan requested changes

2020-10-05 22:28 UTC, mars-lan commented on .github/ISSUE_TEMPLATE/--bug-report.md
> +assignees: ""
Is this a spotless change as well?

2020-10-05 22:28 UTC, mars-lan commented on build.gradle
> +    classpath 'com.diffplug.spotless:spotless-plugin-gradle:5.6.1'
order plugins alphabetically?

2020-10-05 22:28 UTC, mars-lan commented on docs/what/entity.md
> +**Tournament Table** | Tournament | Year | Winner | | ------- | --------- | --------- | | Indiana Invitational | 1998 |
This makes table super hard to read?

2020-10-05 22:28 UTC, mars-lan commented on docs/rfc/templates/000-template.md
> +> Why should we _not_ do this? Please consider the impact on teaching DataHub, on the integration of this feature with
Does spotless prefer italic over bold?

2020-10-05 23:40 UTC, jplaisted commented on .github/ISSUE_TEMPLATE/--bug-report.md
> +assignees: ""
Yes

2020-10-05 23:43 UTC, mars-lan commented on .github/ISSUE_TEMPLATE/--bug-report.md
> +assignees: ""
How come it didn't touch the other single quotes below?

2020-10-05 23:43 UTC, jplaisted commented on docs/rfc/templates/000-template.md
> +> Why should we _not_ do this? Please consider the impact on teaching DataHub, on the integration of this feature with
`*` and `_` are both italic, so it standardizes on `_` for consistency. `**` is bold.

*star*
_underscore_
**double star**

2020-10-05 23:43 UTC, jplaisted commented on docs/what/entity.md
> +**Tournament Table** | Tournament | Year | Winner | | ------- | --------- | --------- | | Indiana Invitational | 1998 |
Same thing as before. This wasn't an actual heading and had no whitespace so spotless collapsed it. Fixed.

2020-10-05 23:44 UTC, mars-lan commented on docs/rfc/templates/000-template.md
> +> Why should we _not_ do this? Please consider the impact on teaching DataHub, on the integration of this feature with
Got it.

2020-10-05 23:45 UTC, mars-lan commented on docs/what/entity.md
> +**Winner Table** | Winner | Birthday | Birth year | | ------- | --------- | --------- | | Chip Masterson | 14 March |
More tables to fix?

2020-10-05 23:53 UTC, jplaisted commented on docs/what/entity.md
> +**Winner Table** | Winner | Birthday | Birth year | | ------- | --------- | --------- | | Chip Masterson | 14 March |
Done, thanks. Verified these are the only tables by checking out master and running

```
find . -name '*.md' | xargs grep -l '^|' | grep -v build/
```

2020-10-05 23:56 UTC, jplaisted commented on .github/ISSUE_TEMPLATE/--bug-report.md
> +assignees: ""
Those are in actual markdown. I'm not sure what the `---` section is, but seems to be some metadata that spotless is aware of.

2020-10-05 23:57 UTC, jplaisted commented on .github/ISSUE_TEMPLATE/--bug-report.md
> +assignees: ""
It's YAML

2020-10-06 03:06 UTC, mars-lan commented on .github/ISSUE_TEMPLATE/--bug-report.md
> +assignees: ""
Interesting way to mix YAML inside of MD :)

2020-10-06 03:10 UTC, mars-lan commented on docs/rfc/templates/000-template.md
> +> Why should we _not_ do this? Please consider the impact on teaching DataHub, on the integration of this feature with
Actually seems like underscore is discouraged? It also looks less natural than `*` IMHO: https://www.markdownguide.org/basic-syntax/#italic

2020-10-06 16:05 UTC, jplaisted commented on docs/rfc/templates/000-template.md
> +> Why should we _not_ do this? Please consider the impact on teaching DataHub, on the integration of this feature with
Prettier is opinionated enough where I don't think they have an option for this.

https://prettier.io/docs/en/option-philosophy.html

Part of the point of prettier/spotless/_any formatter_ is to avoid this kind of debate, imo.

2020-10-06 16:26 UTC, mars-lan commented on docs/rfc/templates/000-template.md
> +> Why should we _not_ do this? Please consider the impact on teaching DataHub, on the integration of this feature with
Seems like the wrong opinion to have given that `_` may not get rendered correctly in all cases. Never mind.

2020-10-06 16:27 UTC, mars-lan approved these changes

2020-10-06 16:49 UTC, jplaisted commented on docs/rfc/templates/000-template.md
> +> Why should we _not_ do this? Please consider the impact on teaching DataHub, on the integration of this feature with
It seems like they target common mark?

https://github.com/prettier/prettier/issues/3728

2020-10-06 18:41 UTC, merged