feat: add type to MAE payload && update docs
linkedin/datahub-gma pull request #300
Opened 2023-10-02 17:30 UTC by JiaoMaWHU

## Summary
1. add a `MetadataEventType` generic enum with three value.
2. include this enum in MAE payload
3. update doc with https://github.com/linkedin/datahub-gma/pull/299

## Testing
./gradlew build

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

2023-10-02 21:01 UTC, jsdonn requested changes

2023-10-02 21:01 UTC, jsdonn commented on dao-api/src/main/pegasus/com/linkedin/metadata/events/MetadataEventType.pdl
> +namespace com.linkedin.metadata.events
are we adding this to both MCE and MAE? will you add to MCE in a later PR?

2023-10-02 21:10 UTC, JiaoMaWHU commented on dao-api/src/main/pegasus/com/linkedin/metadata/events/MetadataEventType.pdl
> +namespace com.linkedin.metadata.events
I will not add it into MCE now. But the name `MetadataEventType` is trying to accommodate such need. We can reuse this payload if MCE needs it in the future.

2023-10-02 21:10 UTC, JiaoMaWHU commented on dao-api/src/main/pegasus/com/linkedin/metadata/events/MetadataEventType.pdl
> +   * Default type. Standard processing strategy applies.
Sure, that's a good suggestion.

2023-10-02 21:10 UTC, JiaoMaWHU commented on dao-api/src/main/pegasus/com/linkedin/metadata/events/MetadataEventType.pdl
> +  BACKILL
will update

2023-10-02 21:10 UTC, JiaoMaWHU commented on dao-api/src/main/pegasus/com/linkedin/metadata/events/MetadataEventType.pdl
> +   * Indicates this event is to bootstrap a new type of metadata.
Yes. But your comment made me realize BOOTSTRAP is not limited to new metadata onboarding, I will update the doc.

2023-10-03 15:55 UTC, yangyangv2 commented on dao-api/src/main/pegasus/com/linkedin/metadata/events/MetadataEventType.pdl
> +   * Default type. Standard processing strategy applies.
How about MetadataIngestionMode?

2023-10-03 22:02 UTC, jsdonn approved these changes
lgtm

2023-10-03 22:11 UTC, merged