Schema Versioning Ingestion Logic
linkedin/datahub-gma pull request #352
Opened 2024-02-06 17:53 UTC by schuangv2

WIP

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2024-02-07 18:12 UTC, edwinalu commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +        || oldValue != null && newValue != null && equalityTester.equals(oldValue, newValue) // values are equal
Would the semantic version be part of the value (oldValue and newValue)?

The logic is correct, but could you please put parentheses around the condition in line 356 to avoid any confusion, and also in case of changes later?

2024-02-07 18:37 UTC, edwinalu approved these changes
Thanks for adding the ingestion logic for semantic versioning!

2024-02-07 18:39 UTC, schuangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +        || oldValue != null && newValue != null && equalityTester.equals(oldValue, newValue) // values are equal
Thanks @edwinalu. 
_Would the semantic version be part of the value (oldValue and newValue)?_
oldValue/newValue are records that may or may not contain the field baseSemanticVersion. The aspectVersionComparator() accounts for both possibilities.

_The logic is correct, but could you please put parentheses around the condition in line 356 to avoid any confusion, and also in case of changes later?_
Good point, I've added the parantheses.

2024-02-07 21:10 UTC, RealChrisL commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +    } else { //newVerMap != null && oldVerMap != null)
remove the right parenthesis in the comment?

2024-02-07 21:10 UTC, RealChrisL commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +      int[] newVerArr = { newVerMap.getInteger("major").intValue(), newVerMap.getInteger("minor").intValue(),
Please put final as possible in variables.

2024-02-07 22:36 UTC, schuangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +    } else { //newVerMap != null && oldVerMap != null)
@RealChrisL thanks for the catch! Fixed.

2024-02-07 22:36 UTC, schuangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +      int[] newVerArr = { newVerMap.getInteger("major").intValue(), newVerMap.getInteger("minor").intValue(),
@RealChrisL thanks for the tip, I updated the code.

2024-02-08 17:41 UTC, RealChrisL approved these changes

2024-02-09 16:19 UTC, yangyangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +  protected int aspectVersionComparator(@Nonnull RecordTemplate newValue, @Nonnull RecordTemplate oldValue) {
the @Nonnull both `newValue` and `oldValue` is not guaranteed, right?

2024-02-09 16:20 UTC, yangyangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +    final DataMap newVerMap = newValue != null ? newValue.data().getDataMap("baseSemanticVersion") : null;
you will need to handle the case either newValue or oldValue is null

2024-02-09 16:21 UTC, yangyangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +    final DataMap newVerMap = newValue != null ? newValue.data().getDataMap("baseSemanticVersion") : null;
Can we make "baseSemanticVersion" a constant?

2024-02-09 16:24 UTC, yangyangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +
please add comments to explain the scenarios

1. if neither new nor old has version, consider as equal
2. if only new has version, it will override the old value regardless equal or not
3. if old value has version, but new doesn't have version, it will ignore the new ingestion.
4. version comparison logic ..

2024-02-09 16:27 UTC, yangyangv2 commented on dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java
> +  @Test(description = "Test MAE emission triggered by incoming aspects with higher versions")
Thanks for writing these cases! 

Please also add two cases for either newValue and oldValue is null.

2024-02-09 16:42 UTC, yangyangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +  protected int aspectVersionComparator(@Nonnull RecordTemplate newValue, @Nonnull RecordTemplate oldValue) {
This would cause assertionFailure when `newValue != null` and `oldValue == null` 

 ---- For all fresh ingestions.

2024-02-09 16:49 UTC, yangyangv2 requested changes
aspectVersionComparator() needs to handle case

newValue != null and oldValue == null or
newValue == null and oldValue =! null

The current implementation will break all the fresh ingestions

2024-02-09 18:00 UTC, schuangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +  protected int aspectVersionComparator(@Nonnull RecordTemplate newValue, @Nonnull RecordTemplate oldValue) {
Thanks @yangyangv2. I have removed the @nonNull check. The first few lines in aspectVersionComparator handles null values.

2024-02-09 19:36 UTC, schuangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +    final DataMap newVerMap = newValue != null ? newValue.data().getDataMap("baseSemanticVersion") : null;
Thanks @yangyangv2 . After I removed `@Nonnull`, the code does handle null inputs. To elaborate,

- If any of the values are null, the ternary logic will keep them as null
- Logic in the rest of the comparator treats null as lowest ranking. This is one standard way of setting up a comparator. 
- With this logic, we will get the following behavior that matches our design:

| newValue | oldValue | newVerMap | oldVerMap | Comparator output | Behavior |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Null | Not Null | Null | Not Null | -1 | Skip write |
| Not Null  | Null  | Not Null | Null | 1 | Do not skip write  |

I made this clearer by adding comments and a aspectVersionSkipWrite() function.

2024-02-09 19:37 UTC, schuangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +    final DataMap newVerMap = newValue != null ? newValue.data().getDataMap("baseSemanticVersion") : null;
@yangyangv2  thanks, I have made the change.

2024-02-09 19:45 UTC, schuangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +
thanks @yangyangv2 . I have added more comments to explain the scenarios.

2024-02-09 19:47 UTC, schuangv2 commented on dao-api/src/test/java/com/linkedin/metadata/dao/BaseLocalDAOTest.java
> +  @Test(description = "Test MAE emission triggered by incoming aspects with higher versions")
Thanks @yangyangv2 . I can't add null cases here because _dummyLocalDAO.add() does not accept null inputs. I have added null tests to testAspectVersionSkipWrite().

2024-02-09 19:47 UTC, schuangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +      final int[] newVerArr = { newVerMap.getInteger("major").intValue(), newVerMap.getInteger("minor").intValue(),
@yangyangv2 thanks, I have made the changes.

2024-02-09 19:51 UTC, schuangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +
@yangyangv2 Also added function aspectVersionSkipWrite() and tests to explicity call out the behavior and make it easier to understand.

2024-02-09 20:35 UTC, yangyangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +        || (aspectVersionSkipWrite(newValue, oldValue)) // newValue ver < oldValue ver
Thanks for addressing bug. A second thought on this behavior:

if the incoming version is greater, should we run the update regardless the equality check? or we only accept ingestion when the version is higher?

Given: new (1.0, status = true), old (0.9, status = true)

should the ending state be:

A: new (1.0, status = true)
B: old (0.9, status = true)

@edwinalu , @edwinalu , @jsdonn

2024-02-09 20:36 UTC, yangyangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +  protected int aspectVersionComparator(RecordTemplate newValue, RecordTemplate oldValue) {
nit: put a @Nullable to both param

2024-02-09 20:38 UTC, edwinalu commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +        || (aspectVersionSkipWrite(newValue, oldValue)) // newValue ver < oldValue ver
Yes, the higher version should get persisted, and in @yangyangv2 's example, the end state should be A: new (1.0, status = true)

2024-02-09 20:41 UTC, yangyangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +        || (aspectVersionSkipWrite(newValue, oldValue)) // newValue ver < oldValue ver
this logic is essentially saying, 

if the new version is smaller, the ingestion will be dropped
if the new version is larger or equal, it will do the equality check

or should this be

if the new version is larger, ignore the equal check and do the update
if the new version is equal, then do the equality check.

2024-02-09 20:51 UTC, schuangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +        || (aspectVersionSkipWrite(newValue, oldValue)) // newValue ver < oldValue ver
@yangyangv2 @edwinalu thanks for the comments. 
@edwinalu I just added a test and confirmed that the higher version will be persisted, even if values are equal. The reason this happens is that the version is included in the equality check. Eg if we bump the version without changing anything else, equality check will return false and new version will be written.

2024-02-09 21:00 UTC, schuangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +        || (aspectVersionSkipWrite(newValue, oldValue)) // newValue ver < oldValue ver
@yangyangv2 I think we are almost on the same page. The logic is 

- if the new version is smaller, the ingestion will be dropped
- if the new version is equal, it will do the equality check
- if new version is larger, it will fail equality check. Ingestion will occur.

2024-02-09 21:01 UTC, edwinalu commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +        || (aspectVersionSkipWrite(newValue, oldValue)) // newValue ver < oldValue ver
Thanks for confirming and adding the test case!

2024-02-09 21:14 UTC, schuangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +  protected int aspectVersionComparator(RecordTemplate newValue, RecordTemplate oldValue) {
@yangyangv2 thanks, I've added the change.

2024-02-09 21:52 UTC, yangyangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +        || (aspectVersionSkipWrite(newValue, oldValue)) // newValue ver < oldValue ver
With this logic the outcome will be B: old (0.9, status = true). 

because  1.0 > 0.9, so `(aspectVersionSkipWrite(newValue, oldValue))` will be `false` and the equity check will be invoked. Since both have `status = true` then the new ingestion (1.0, status = true) will be dropped and 

B: old (0.9, status = true) 

will be the outcome.

2024-02-09 22:05 UTC, yangyangv2 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +        || (aspectVersionSkipWrite(newValue, oldValue)) // newValue ver < oldValue ver
Nvm, synced offline and the equalityTester will capture the version difference. 

I'll let this PR pass due to its urgency. But MG team should review the equalityTest whether to exclude auxiliary metadata in the future we will have other control metadata such as writeMode. We shouldn't let equalityTest be polluted with these control attributes.

@jsdonn @zhixuanjia

2024-02-09 22:08 UTC, yangyangv2 approved these changes
Thanks for addressing all the comments!

2024-02-09 22:29 UTC, merged

2024-02-09 22:40 UTC, jsdonn commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +        || (aspectVersionSkipWrite(newValue, oldValue)) // newValue ver < oldValue ver
I wonder if we could have the use case-specific comparison logic on the producer side. In this example, if SI can detect the current version we have stored in db (through get API call), and they can add the OVERRIDE ingestion mode if the comparison returns true.