Adding support for non dollar virtual columns names
linkedin/datahub-gma pull request #353
Opened 2024-02-07 01:37 UTC by rakhiagr

##Summary
Adding support for virtual column names without $ character. 

##Testing Done
./gradlew build

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2024-02-09 22:24 UTC, jsdonn requested changes

2024-02-12 17:40 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java
> +      @Nullable URN lastUrn, int pageSize, boolean nonDollarVirtualColumnsEnabled) {
we shouldn't need to add `nonDollarVirtualColumnsEnabled` for each calls. Can you make it a member field of EbeanLocalAccess and set at construction time?

2024-02-12 18:41 UTC, jsdonn reviewed
LGTM but please address @yangyangv2 's comment

2024-02-12 23:18 UTC, rakhiagr commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +    return _localAccess.countAggregate(indexFilter, indexGroupByCriterion, true);
Done

2024-02-12 23:18 UTC, rakhiagr commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/IEbeanLocalAccess.java
> +  default Map<String, Long> countAggregate(@Nullable IndexFilter indexFilter,
Done

2024-02-12 23:18 UTC, rakhiagr commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java
> +    if (nonDollarVirtualColumnsEnabled) {
Added

2024-02-12 23:24 UTC, jsdonn commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  EbeanLocalDAO(@Nonnull Class<ASPECT_UNION> aspectUnionClass, @Nonnull BaseTrackingMetadataEventProducer producer,
Do we need both a new constructor and the set method? Let's just pick one and stick with it. Keep it simpler

2024-02-12 23:26 UTC, jsdonn commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
> +  private final boolean _nonDollarVirtualColumnsEnabled = false;
You can do a similar setup to EbeanLocalDAOTest https://github.com/linkedin/datahub-gma/blob/8bed271cd75a3e667f76ee7e11fa1b33d525aef8/dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalDAOTest.java#L138

2024-02-12 23:56 UTC, rakhiagr commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  EbeanLocalDAO(@Nonnull Class<ASPECT_UNION> aspectUnionClass, @Nonnull BaseTrackingMetadataEventProducer producer,
This constructor is only for testing purpose, to initialize _localAccess with correct parameters @jsdonn

2024-02-13 00:05 UTC, rakhiagr commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
> +  private final boolean _nonDollarVirtualColumnsEnabled = false;
I did it for simplicity, but I will change it.

2024-02-13 00:18 UTC, jsdonn approved these changes
LGTM, please get @yangyangv2 's approval too!

2024-02-14 01:07 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +  EbeanLocalDAO(@Nonnull Class<ASPECT_UNION> aspectUnionClass, @Nonnull BaseTrackingMetadataEventProducer producer,
we shouldn't use setter for `_nonDollarVirtualColumnsEnabled`. which should be finalized at construction time. 

The setting this value from constructor is a good option, can we make it formal constructor? instead of using setter methods?

And, to avoid changing constructors again and again when more params are added. Consider creating a `EBeanDAOConfig` POJO class and wrapping the `_nonDollarVirtualColumnsEnabled` into it. Such as 

```
@Data
public class EBeanDAOConfig {
  boolean nonDollarVirtualColumnsEnabled = false
}
```

So the Constructor will be
```
 EbeanLocalDAO(@Nonnull Class<ASPECT_UNION> aspectUnionClass, @Nonnull BaseTrackingMetadataEventProducer producer,
 @Nonnull EbeanServer server, @Nonnull ServerConfig serverConfig, @Nonnull Class<URN> urnClass, @Nonnull SchemaConfig schemaConfig,
@Nonnull EBeanDAOConfig ebeanDAOConfig
```

And the compatible constructors can be
```
 EbeanLocalDAO(@Nonnull Class<ASPECT_UNION> aspectUnionClass, @Nonnull BaseTrackingMetadataEventProducer producer,
 @Nonnull EbeanServer server, @Nonnull ServerConfig serverConfig, @Nonnull Class<URN> urnClass) {

  this(aspectUnionClass, producer, server, serverConfig, urnClass, new EBeanDAOConfig())
}
```

2024-02-14 04:20 UTC, yangyangv2 reviewed
a lot better! thanks for addressing the comments!

2024-02-14 04:20 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
> +  private EBeanDAOConfig config;
nit: final

2024-02-14 04:20 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
> +  private final boolean _nonDollarVirtualColumnsEnabled;
since you have `EBeanDAOConfig config`, you don't need to maintain another local copy.

2024-02-14 04:20 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
> +    _nonDollarVirtualColumnsEnabled = nonDollarVirtualColumnsEnabled;
you can instantiate the EbeanDAOConfig here instead of on the init() method

2024-02-14 04:20 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
> +    config.setNonDollarVirtualColumnsEnabled(_nonDollarVirtualColumnsEnabled);
move line 90, 91 to 66.

2024-02-14 04:20 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/localrelationship/EbeanLocalRelationshipQueryDAOTest.java
> +    _eBeanDAOConfig = new EBeanDAOConfig();
same here, move 84,85 to line 71

2024-02-14 06:52 UTC, rakhiagr commented
/rerun-check Custom Validations

2024-02-14 13:37 UTC, yangyangv2 approved these changes
Nice work, have a few nit suggestions left, but not mandatory. 

thanks for addressing all the comments!

2024-02-14 13:37 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java
> +    String groupByColumn = getGeneratedColumnName(indexGroupByCriterion.getAspect(), indexGroupByCriterion.getPath(), _nonDollarVirtualColumnsEnabled);
reason to remove the `final`?

2024-02-14 13:37 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +      _localAccess = new EbeanLocalAccess<>(server, serverConfig, urnClass, _urnPathExtractor, _nonDollarVirtualColumnsEnabled);
nit: consider using `ebeanDAOConfig.isNonDollarVirtualColumnsEnabled()` to replace all the `_nonDollarVirtualColumnsEnabled`.

2024-02-14 13:37 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java
> +      sqlBuilder.append(" WHERE ").append(SQLStatementUtils.whereClause(filter, SUPPORTED_CONDITIONS, null, _nonDollarVirtualColumnsEnabled));
same here, with the presence of `EBeanDAOConfig`, ` _nonDollarVirtualColumnsEnabled` is not necessary

2024-02-14 13:37 UTC, yangyangv2 commented on dao-impl/ebean-dao/src/test/java/com/linkedin/metadata/dao/EbeanLocalAccessTest.java
> +  @Factory(dataProvider = "inputList")
Thanks for creating this test suit!

2024-02-14 20:03 UTC, rakhiagr commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalAccess.java
> +    String groupByColumn = getGeneratedColumnName(indexGroupByCriterion.getAspect(), indexGroupByCriterion.getPath(), _nonDollarVirtualColumnsEnabled);
Left by mistake after so many iterations, corrected.

2024-02-14 20:03 UTC, rakhiagr commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java
> +      _localAccess = new EbeanLocalAccess<>(server, serverConfig, urnClass, _urnPathExtractor, _nonDollarVirtualColumnsEnabled);
Updated

2024-02-14 20:03 UTC, rakhiagr commented on dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalRelationshipQueryDAO.java
> +      sqlBuilder.append(" WHERE ").append(SQLStatementUtils.whereClause(filter, SUPPORTED_CONDITIONS, null, _nonDollarVirtualColumnsEnabled));
Updated

2024-02-14 21:07 UTC, merged