implement dual write in BaseAspectRoutingResource
linkedin/datahub-gma pull request #420
Opened 2024-09-11 00:58 UTC by jsdonn

## Summary
d

## Testing Done
d
## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2024-09-11 11:21 UTC, ybz1013 reviewed
I dont really have the context from #410. Just left some comments.

2024-09-11 11:21 UTC, ybz1013 commented on restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
> -            aspect = preUpdateRouting(urn, aspect);
question: does this mean the old code will execute preUpdateRouting twice if the aspect is registered in the _restliPreUpdateAspectRegistry AND not a routed aspect? Once here, and once in the add function.

2024-09-11 11:21 UTC, ybz1013 commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +  public <ASPECT extends RecordTemplate> ASPECT addSimple(@Nonnull URN urn, @Nonnull ASPECT newValue,
after looking at #410, this addSimple looks the same as the old add function.

2024-09-11 15:54 UTC, rakhiagr requested changes

2024-09-11 15:54 UTC, rakhiagr commented on restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
>            String aspectFQCN = aspect.getClass().getCanonicalName();
This was added specifically for DatasetAccountableOwnership aspect to skip the normal ingestion once the preUpdateRouting is done and not go to OwnershipGMS. Can you move this lines after we call preUpdateRouting (Line 330).
```
// Get the fqcn of the aspect class
          String aspectFQCN = aspect.getClass().getCanonicalName();
          //TODO: META-21112: Remove this check after adding annotations at model level; to handle SKIP/PROCEED for preUpdateRouting
          if (SKIP_INGESTION_FOR_ASPECTS.contains(aspectFQCN)) {
            return;
          }
```

2024-09-11 15:54 UTC, rakhiagr commented on restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
>            String aspectFQCN = aspect.getClass().getCanonicalName();
Same as above, move to Line 378.

2024-09-11 18:08 UTC, hongliu2024 commented on restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
>            String aspectFQCN = aspect.getClass().getCanonicalName();
`DatasetAccountableOwnership` is specially handled? It needs to call `urn converter` and then write to TMS?

2024-09-11 18:08 UTC, hongliu2024 commented on restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
>            String aspectFQCN = aspect.getClass().getCanonicalName();
Somehow I remember `DatasetAccountableOwnership` is deprecated and got replaced by `AccountableOwnership`?

2024-09-11 18:35 UTC, jsdonn commented on restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
>            String aspectFQCN = aspect.getClass().getCanonicalName();
got it thanks

2024-09-11 18:47 UTC, jsdonn commented on restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
> -            aspect = preUpdateRouting(urn, aspect);
Yes exactly, old code would have executed preUpdateRouting twice in the case you mentioned.

2024-09-13 01:04 UTC, jsdonn commented on restli-resources/src/main/java/com/linkedin/metadata/restli/BaseAspectRoutingResource.java
> +                aspect = preUpdateRouting(urn, aspect);
Added.

2024-09-16 18:46 UTC, jsdonn commented on dao-api/src/main/java/com/linkedin/metadata/dao/BaseLocalDAO.java
> +  public <ASPECT extends RecordTemplate> ASPECT addSimple(@Nonnull URN urn, @Nonnull ASPECT newValue,
Changed to addSkipPreIngestionUpdates

2024-09-16 21:20 UTC, hongliu2024 approved these changes
Should we conduct some testing in EI before promoting to corp?

2024-09-16 21:34 UTC, rakhiagr commented on restli-resources/src/test/java/com/linkedin/metadata/restli/BaseAspectRoutingResourceTest.java
> +    verify(_mockLocalDAO, times(1)).addSkipPreIngestionUpdates(any(), any(), any(), any(), any());
Can we do `verify(_mockLocalDAO, times(1)).addSkipPreIngestionUpdates(eq(urn), eq(foo), any(), any(), any());`

2024-09-16 23:32 UTC, rakhiagr approved these changes
Looks good, thank you for addressing all the comments

2024-09-16 23:35 UTC, merged