fix: do not split value of a filter by comma for an urn
linkedin/datahub-gma pull request #49
Opened 2020-11-18 20:18 UTC by jywadhwani

Currently clients are using `comma` to provide multiple values a key can take while issuing filtered search query. Elasticsearch DAO splits the value by comma delimiter to populate the `terms` query. This does not work well when the value is an `Urn` with comma as some of the characters.
This change ensure we do not split the value by comma when the value is an Urn. Ideally we should be using the `OR` criterion to provide multiple values a key can take. But this will need changes on the client side before we stop supporting the `comma` feature to specify multiple values on the DAO side.

## Checklist

- [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [X] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2020-11-18 20:45 UTC, jplaisted requested changes

2020-11-18 20:45 UTC, jplaisted commented on dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
> +        Urn.createFromString(criterion.getValue());
This is still just a heuristic.

The better thing to do would be to change `Criteron` to have a list of values rather than a comma delimited value that we then have to parse. You get the same issue here if there's some legitimate string that has a comma in it that isn't an URN.

I don't think this work around is worth it. Instead, we should work to fix clients ASAP, and then remove this splitting behavior.

2020-11-18 20:45 UTC, jplaisted commented on dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
> +        Urn.createFromString(criterion.getValue());
Whoops, sorry, the better thing to do* would be what you suggested in the OP (fix clients and then remove behavior).

2020-11-18 21:56 UTC, camelliazhang commented on dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
> +        Urn.createFromString(criterion.getValue());
Agree with @jplaisted . Split with comma was a hack solution already. There are a few options here, @keremsahin1 had proposed search filter redesign, let's discuss more on this internally. 
Meanwhile, for search 'Filter', have we explored the advanced search? That way we can leverage ES's out of box query parser. https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_field_names

2020-11-18 21:56 UTC, camelliazhang commented on dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
> +        Urn.createFromString(criterion.getValue());
Also, we need to think/discuss is whether we need to keep both 5 & 7 DAO. Quite some duplicated codes here.

2020-11-18 22:04 UTC, keremsahin1 commented on dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
> +        Urn.createFromString(criterion.getValue());
Agreed with @jplaisted and @camelliazhang . Some time ago I shared a proposal to redesign filter to make it cover different filtering use cases - without hacks. We can iterate more on that and prioritize the work if necessary.

I would say let's not try to add more hacks here and opt for a long term, more robust solution.

2020-11-19 18:03 UTC, jplaisted commented on dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
> +        Urn.createFromString(criterion.getValue());
Since this apparently blocking another team, let's considering adding this.

HOWEVER, and this applies to ALL workarounds like this, please document (in the code, in comments) why this code is the way it is, and add a TODO that links to a ticket to clean it up.

2020-11-19 21:04 UTC, jywadhwani commented on dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
> +        Urn.createFromString(criterion.getValue());
@camelliazhang  we will need to support both DAOs in `datahub-gma` till we remove support for ES5 in `datahub`.
I have created an issue for tracking purpose https://github.com/linkedin/datahub-gma/issues/51

2020-11-19 22:01 UTC, jplaisted requested changes

2020-11-19 22:01 UTC, jplaisted commented on dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
> +      if (criterion.getValue().startsWith("urn:li:")) {
Please a comment which states:

- What this is doing
- Why we're doing it
- Add a `TODO(github issue url): explanation of todo` for the long term solution

2020-11-20 00:08 UTC, jywadhwani commented on dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
> +      if (criterion.getValue().startsWith("urn:li:")) {
Added, hope it looks good.

2020-11-20 00:35 UTC, camelliazhang commented on dao-impl/elasticsearch-dao-7/src/test/resources/UrnFilterQuery.json
> +              "urn:li:entity:(foo,bar,baz)"
Add a test where a value is sth like "a,b,c"?

2020-11-20 00:39 UTC, jywadhwani commented on dao-impl/elasticsearch-dao-7/src/test/resources/UrnFilterQuery.json
> +              "urn:li:entity:(foo,bar,baz)"
We already have one where value is `"value1, value2 "` which should cover this scenario?

2020-11-20 06:50 UTC, camelliazhang commented on dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
> +      if (criterion.getValue().startsWith("urn:li:")) {
This regex works internally, but what about open source? urn:li seems be specific to LinkedIn?

2020-11-20 06:53 UTC, jywadhwani commented on dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
> +      if (criterion.getValue().startsWith("urn:li:")) {
The definition of `Urn` is similar to what we have internally https://github.com/linkedin/datahub-gma/blob/master/core-models/src/main/javaPegasus/com/linkedin/common/urn/Urn.java

2020-11-20 06:54 UTC, jywadhwani commented on dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
> +      if (criterion.getValue().startsWith("urn:li:")) {
@jplaisted can you please confirm?

2020-11-20 07:02 UTC, camelliazhang commented on dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
> +      if (criterion.getValue().startsWith("urn:li:")) {
Looks like the breaking change was indeed made. Will approve this PR to un-block customers first.

2020-11-20 07:02 UTC, camelliazhang approved these changes
Thanks for the prompt fix!

2020-11-20 07:17 UTC, merged

2020-11-20 17:38 UTC, jplaisted commented on dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
> +      if (criterion.getValue().startsWith("urn:li:")) {
In the future, this stuff really should just go right next to the actual line, not in java doc. Java doc should be reserved for documenting the API, and any hacks/workarounds shouldn't go in there :p

2020-11-20 17:40 UTC, jywadhwani commented on dao-impl/elasticsearch-dao-7/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java
> +      if (criterion.getValue().startsWith("urn:li:")) {
Thanks!