Fix broken GMA onboarding guide
linkedin/datahub-gma pull request #93
Opened 2021-04-09 17:58 UTC by jywadhwani

GMA onboarding guide is broken. This patch replaces it with the guide to onboard a data source.

## Checklist

- [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2021-04-09 22:18 UTC, shirshanka approved these changes
LGTM!

2021-04-10 00:30 UTC, shirshanka requested changes
Suggest we remove this link and delete the doc being referred to, since we have updated docs for this in the datahub project that are more accurate.

2021-04-10 00:30 UTC, shirshanka commented on README.md
> +- [Data Source Onboarding Guide](docs/how/data-source-onboarding.md)
We have significantly revamped ingestion docs. 
They are hosted on the datahub project at: https://datahubproject.io/docs/metadata-ingestion

So probably drop this link and delete the data-source-onboarding.md doc from gma, because it is out of date.

2021-04-10 23:59 UTC, jplaisted commented on README.md
> +- [Data Source Onboarding Guide](docs/how/data-source-onboarding.md)
The docs weren't very cleaning split when GMA was moved out, I made this ticket.

https://github.com/linkedin/datahub-gma/issues/8

Might be a good time to revisit all our docs. Or just have GMA's docs point to DataHub and centralize everything there...

2021-04-12 19:46 UTC, shirshanka approved these changes
LGTM

2021-04-12 19:48 UTC, merged